name: Generic Package CI
on: push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm run-script test-ci

    - run: npm run-script build-ci okta_native
    - run: test -f distributions/okta_native/okta_native.zip
    - run: npm run-script build-ci rotate_key_pair
    - run: test -f distributions/rotate_key_pair/rotate_key_pair.zip

    - uses: actions/upload-artifact@v2
      with:
        name: packages_${{ matrix.node-version }}
        path: distributions/*/*.zip
