name: Upload Release Assets

on:
  push:
    # Match against refs/tags
    tags:
    - 'v*' # Push events matching v*, e.g. v1.0.0, v1.1.0

jobs:
  build:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run tests
        run: npm run-script test-ci

      - name: Build okta_native
        run: npm run-script build-ci okta_native
      - name: Build rotate_key_pair
        run: npm run-script build-ci rotate_key_pair

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./distributions/okta_native/okta_native.zip
            ./distributions/rotate_key_pair/rotate_key_pair.zip
